### ISSUE TITLE
Can not install helm-unittest at v0.2.9

### ISSUE THREAD

**Issue by edarha** [quintush/helm-unittest#178]
- I encounter the issue when i try to install `helm-unittest` by this command `helm plugin install https://github.com/quintush/helm-unittest` with the latest version `v0.2.9`. 
- my error: 

```
Run helm plugin install https://github.com/quintush/helm-unittest
cygpath: not found
./install-binary.sh: 16: cygpath: not found
./install-binary.sh: 19: [[: not found
./install-binary.sh: 72: [[: not found
Support linux-amd6[4](https://github.com/manabie-com/backend/actions/runs/3124909320/jobs/5068778436#step:4:5)
Retrieving https://api.github.com/repos/quintush/helm-unittest/releases/latest
./install-binary.sh: 82: [[: not found
Downloading https://github.com/quintush/helm-unittest/releases/download/v0.2.9/helm-unittest-linux-amd[6](https://github.com/manabie-com/backend/actions/runs/3124909320/jobs/5068778436#step:4:7)4-0.2.[9](https://github.com/manabie-com/backend/actions/runs/3124909320/jobs/5068778436#step:4:10).tgz to location /tmp/_dist/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

[10](https://github.com/manabie-com/backend/actions/runs/3124909320/jobs/5068778436#step:4:11)0 19.0M  100 19.0M    0     0  69.9M      0 --:--:-- --:--:-- --:--:-- 69.9M
./install-binary.sh: [11](https://github.com/manabie-com/backend/actions/runs/3124909320/jobs/5068778436#step:4:12)6: [: linux: unexpected operator
Validating Checksum.
Preparing to install into 
cp: cannot create regular file '': No such file or directory
Error: plugin install hook for "unittest" exited with error
Failed to install helm-unittest
For support, go to https://github.com/kubernetes/helm
```

**Comment by quintush** [comment]
Hello @edarha,

I just pushed an update to stabelize the installation script.
Try to install it again using the same command (with latest it will pick the latest commit). 

If you still have troubles, installing please give me some information what os you are installing the plugin.
Also cleaning-up the helm cache path (https://helm.sh/docs/helm/helm/, there is a table showing the default locations of the folders) can help solving the problem, as the plugin installer is caching it's installation.

Greetings,
@quintush

**Comment by artiz** [comment]
Hey, error still not fixed for Linux,  `HELM_PLUGIN_PATH` is defined as empty string

```
cygpath: not found
./install-binary.sh: 16: cygpath: not found
Support linux-amd64
Retrieving https://api.github.com/repos/quintush/helm-unittest/releases/latest
Downloading https://github.com/quintush/helm-unittest/releases/download/v0.2.9/helm-unittest-linux-amd64-0.2.9.tgz to location /tmp/_dist/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 19.0M  100 19.0M    0     0   168k      0  0:01:55  0:01:55 --:--:-- 58625
Validating Checksum.
Preparing to install into
cp: cannot create regular file '': No such file or directory
Failed to install helm-unittest
For support, go to https://github.com/kubernetes/helm
Error: plugin install hook for "unittest" exited with error
```

**Comment by quintush** [comment]
Hello @artiz,

Thanks for pointing it out.
Did not see the missing path.

Updated the script again with simplification of the path initialization, which should fix the problem.

Greetings,
@quintush

**Comment by artiz** [comment]
@quintush very strange but HELM_PLUGIN_DIR is also empty.  `export HELM_PLUGIN_DIR=$HOME/.local/share/helm` does not fix  the issue

**Comment by quintush** [comment]
Hello @artiz ,

The issue should now be resolved.
Sygwin validation wat triggered, so that the path was reset to "".
I have managed to reproduce the issue van finally verified the correct validation is resolving the issue.

Greetings,
@quintush

**Comment by artiz** [comment]
Hey, @quintush 
Yep all is fine, issue is resolved. Thank you very much.

**Comment by BernhardGruen** [comment]
Hey,

it seems a new install only works if done without version. If I use 0.2.9 as version it still does not work. Is it possible that the git tag needs an update too? Or do you plan releasing a new version anyway?

**Comment by edarha** [comment]
i got this issue 

```
$ helm plugin install https://github.com/quintush/helm-unittest --version 0.2.9
Error: Unable to update repository: exit status 1

$ helm plugin install https://github.com/quintush/helm-unittest 
Error: Unable to update repository: exit status 1
```

**Comment by BernhardGruen** [comment]
Yes, works now. Many thanks for your really fast reaction to this. @quintush

**Comment by quintush** [comment]
> hello @quintush i got this issue
> 
> ```
> $ helm plugin install https://github.com/quintush/helm-unittest --version 0.2.9
> Error: Unable to update repository: exit status 1
> 
> $ helm plugin install https://github.com/quintush/helm-unittest 
> Error: Unable to update repository: exit status 1
> ```

Hello @edarha,

Can you try to remove the plugin (helm plugin remove unittest) and clean the cache (clean the $HOME/.cache/helm/plugin folder and retry installing?

If that still does not work, can you please tell me which linux distro you are using? There are some small differences.

Greetings,
@quintush

**Comment by edarha** [comment]
it works fine now, thanks a lot your of effort @quintush
